### ISSUE TITLE
Collection resources should be passed "raw" to the controller

### ISSUE THREAD

**Issue by Ocramius** [zf-fr/zfr-rest#108]
Right now, we are converting collection resources into paginators during routing.

That is a lossy conversion that makes it very hard to operate on the original collection by keeping the controller or service layer persistence-agnostic.

What I'm suggesting is that the controller should be allowed to get passed in whatever the original collection was, so instead of:

`public function get(Paginator $someResource) {...}`

we'd have 

`public function get($someResource) {...}`

Deciding what to do with the resource (paginate it, slice it, whatever) is up to either the controller, or a method handler, or the view layer.

Routing was absolutely a mistake for this.

**Comment by bakura10** [comment]
No longer apply in #187, as you only receive route params, and are responsible for fetching yourself resources from your service, so you have control on if you want to paginate it or now.
