### ISSUE TITLE
Recursive extraction

### ISSUE THREAD

**Issue by danizord** [zf-fr/zfr-rest#118]
What's the best way to support this? Let's create a `RecursiveHydrator`?
```json
{
    "id": 1,
    "title": "ZfrRest is awesome",
    "author": {
        "id": 50,
        "name": "Michaël Gallego"
    }
}
```

**Comment by bakura10** [comment]
No longer apply with #184. Rendering is now done using template, and ZfrRest will support render sub-resources. So each template is now only responsible to render its own part.
